##<center>__Самостійні завдання__</center>

> Скопіювати блок самостійних завдань в окремий файл ***LastName_CP2.ipynb***

> Інсталюйте необхідні пакети бібліотек Python

In [1]:
import numpy as np
import sympy as sym

### Завдання №1

1. Задати матрицю $A$ розмірності $4х5$ з цілих чисел. 
2. Вивести другий рядок матриці $A$.
3. Вивести третій стовпчик матриці $A$. 
4. Вивести елемент $a_{13}$
5. Транспонувати матрицю $A$
5. Вивести матрицю $B$, яка є частиною матриці $A$ з перших трьох рядків та стовпців.
6. Знайти визначник матриці $B$

In [2]:
A = np.random.randint(10, size=(4, 5))
print(f"Created matrix\n{A}")

Created matrix
[[5 3 0 4 4]
 [3 0 5 7 9]
 [7 3 5 8 2]
 [7 3 0 4 9]]


In [3]:
print(f"Second row {A[1, :]}")

Second row [3 0 5 7 9]


In [4]:
print(f"Third column {A[:, 2]}")

Third column [0 5 5 0]


In [5]:
print(f"Element a13 {A[0, 2]}")

Element a13 0


In [6]:
print(f"Transposed matrix\n{A.transpose()}")

Transposed matrix
[[5 3 7 7]
 [3 0 3 3]
 [0 5 5 0]
 [4 7 8 4]
 [4 9 2 9]]


In [7]:
B = A[:3, :3]
print(f"B matrix\n{B}")

B matrix
[[5 3 0]
 [3 0 5]
 [7 3 5]]


In [8]:
print(f"det(B) = {np.linalg.det(B)}")

det(B) = -14.99999999999998


### Завдання №2

1. Задати матрицю $A$ розмірності $2х3$ з цілих чисел. 
2. Задати матрицю $B$ розмірності $3х2$ з цілих чисел
3. Обчислити добуток $AB$ та $BA$ 
4. Перемножити поелементно $AB^T$ $BA^T$
5. Обчислити вираз $(2A-3B^T)N$, де $N$ - квадратна матриця з одиниць, порядку, що дозволяє оперцію множення


In [9]:
A = np.random.randint(10, size=(2, 3))
print(f"A matrix\n{A}")

A matrix
[[8 1 5]
 [3 5 8]]


In [10]:
B = np.random.randint(10, size=(3, 2))
print(f"B matrix\n{B}")

B matrix
[[5 3]
 [0 2]
 [7 8]]


In [11]:
print(f"AB = \n{A @ B}")

AB = 
[[75 66]
 [71 83]]


In [12]:
print(f"BA = \n{B @ A}")

BA = 
[[49 20 49]
 [ 6 10 16]
 [80 47 99]]


In [13]:
print(f"Elementwise AB^T = \n{np.multiply(A, B.transpose())}")

Elementwise AB^T = 
[[40  0 35]
 [ 9 10 64]]


In [14]:
print(f"Elementwise BA^T = \n{np.multiply(B, A.transpose())}")

Elementwise BA^T = 
[[40  9]
 [ 0 10]
 [35 64]]


In [15]:
N = np.ones((3,2))
temp = 2 * A - 3 * B.transpose()
print(f"(2A−3B^T)N = \n{(2 * A - 3 * B.transpose()) @ N}")

(2A−3B^T)N = 
[[-8. -8.]
 [-7. -7.]]


### Завдання №3

Знайти розв'язок системи лінійних рівнянь
$$\begin{cases}
   2x_1+5x_2-4x_3=-3\\
   3x_1-8x_2+3x_3=11\\
   5x_1+6x_2-4x_3=-1
 \end{cases} $$. 
1. Перевірити за теоремою Кронекера-Капеллі, що система має єдиний розв'язок
1. За допомогою вбудованої функції з бібліотеки Python
2. За допомогою матричного методу
3. За допомогою методу Крамера 
4. Зробити перевірку, що знайдений розв'язок задовільняє систему
5. Знайти власні числа та власні вектори матриці А


In [16]:
A = np.array([[2, 5, -1], [3, -8, 3], [5, 6, -4]])
b = np.array([-1, 11, -1])

In [17]:
A_expanded = np.hstack((A, b[:, np.newaxis]))
print(f"Kronecker-Capelli theorem check = {np.linalg.matrix_rank(A) == np.linalg.matrix_rank(A_expanded)}")

Kronecker-Capelli theorem check = True


In [18]:
np_x = np.linalg.solve(A, b)
np_x

array([ 1.26666667, -0.48571429,  1.1047619 ])

In [19]:
np.allclose(np.dot(A, np_x), b)

True

In [20]:
mat_x = np.linalg.inv(A).dot(b)
mat_x

array([ 1.26666667, -0.48571429,  1.1047619 ])

In [21]:
np.allclose(np.dot(A, mat_x), b)

True

In [22]:
def cramer(A, b):
    D = np.linalg.det(A)
    mat1 = np.array([b, A[:, 1], A[:, 2]])
    mat2 = np.array([A[:, 0], b, A[:, 2]])
    mat3 = np.array([A[:, 0], A[:, 1], b])
    Dx = np.linalg.det([mat1, mat2, mat3])
    X = Dx/D
    
    return X

In [23]:
cramer_x = cramer(A, b)
cramer_x

array([ 1.26666667, -0.48571429,  1.1047619 ])

In [24]:
np.allclose(np.dot(A, cramer_x), b)

True

In [25]:
values, vectors = np.linalg.eig(A)
print(f"Eig values {values}\n Eig vectors\n{vectors}")

Eig values [  3.60817133  -2.65740409 -10.95076724]
 Eig vectors
[[-0.63773473 -0.21747681  0.35118231]
 [-0.34304679  0.38220028 -0.81878328]
 [-0.68964724  0.89812403  0.45416398]]


### Завдання №4

Знайти границі функції:

1. $$\lim_{x\to\infty} \frac{2x^3+3x^2-7}{4x^2+5x-8}$$

2. $$\lim_{x\to\infty} \left(\frac{x+4}{x+8}\right)^{-3x}$$
3. $$\lim_{x\to 0} \frac{x^2+x-12}{\sqrt{x-2}-\sqrt{4-x}}$$
4. $$\lim_{x\to 2} \frac{x^2-5x+6}{x^2-12x+20}$$
5. $$\lim_{x\to 0} \frac{\tan(3x)-\sin(3x)}{2x^2}$$






In [26]:
x = sym.Symbol('x')
y = sym.Symbol('y')

In [27]:
sym.limit((2*x**3 + 3*x**2 - 7)/(4*x**2 + 5*x - 8), x, sym.oo)

oo

In [28]:
sym.limit(((x+4)/(x+8))**(-3*x), x, sym.oo)

exp(12)

In [29]:
sym.limit((x**2 + x - 12)/(sym.sqrt(x - 2) - sym.sqrt(4 - x)), x, 0)

-12/(-2 + sqrt(2)*I)

In [30]:
sym.limit((x**2 - 5*x + 6)/(x**2 - 12*x + 20), x, 2)

1/8

In [31]:
sym.limit((sym.tan(3*x) - sym.sin(3*x))/(2*x**2), x, 0)

0

### Завдання №5

Знайти похідну функцій

1. $$y=x\sin^3(3x)$$
1. $$y=\ln(x^4-\cos^2(x))$$
2. $$y=x^2\tan(2x)+e^{6x}$$
3. Знайти похідні до 3-го порядку включно
$$y=x^2-5\sin(4x)+3^{2x} $$



In [32]:
sym.diff(x*(sym.sin(3*x))**3, x)

9*x*sin(3*x)**2*cos(3*x) + sin(3*x)**3

In [33]:
sym.diff(sym.ln(x**4 - (sym.cos(x))**2), x)

(4*x**3 + 2*sin(x)*cos(x))/(x**4 - cos(x)**2)

In [34]:
sym.diff(x**2 * sym.tan(2*x) + sym.exp(6*x), x)

x**2*(2*tan(2*x)**2 + 2) + 2*x*tan(2*x) + 6*exp(6*x)

In [35]:
function = x**2 - sym.sin(4*x) + 3**(2*x)
sym.diff(function, x)

2*3**(2*x)*log(3) + 2*x - 4*cos(4*x)

In [36]:
sym.diff(function, x, 2)

2*(2*3**(2*x)*log(3)**2 + 8*sin(4*x) + 1)

In [37]:
sym.diff(function, x, 3)

8*(3**(2*x)*log(3)**3 + 8*cos(4*x))

### Завдання №6

Знайти невизначений інеграл

1. $$\int \frac{2-x}{4x^2+16x-12} \,dx$$
1. $$\int \frac{7x-1}{\sqrt{2x^2-x+5}} \,dx$$
3. $$\int \frac{\ln(x)}{x^3} \,dx$$
4. $$\int \frac{x\arccos(2x)}{\sqrt{1-4x^2}} \,dx$$

Обчислити визначений інтеграл

1. $$\int_{1}^{2} 3(x-1)^2 \,dx$$
2. $$\int_{0}^{\pi/2} \sin^3(x) \,dx$$
3. $$\int_{1}^{+\infty} \frac{1}{x^2+4x+13} \,dx$$
4. $$\int_{1}^{+\infty} \frac{2+\sin(x)}{\sqrt{x}},dx$$


∫2−x4x2+16x−12dx

In [38]:
sym.integrate((2 - x)/(4*x**2 + 16*x - 12), x)

-(1/8 + sqrt(7)/14)*log(x + 2 + sqrt(7)) - (1/8 - sqrt(7)/14)*log(x - sqrt(7) + 2)

In [39]:
sym.integrate((7*x - 1)/(sym.sqrt(2 * x**2 - x + 5)), x)

Integral((7*x - 1)/sqrt(2*x**2 - x + 5), x)

In [40]:
sym.integrate(sym.ln(x)/x**3, x)

-log(x)/(2*x**2) - 1/(4*x**2)

In [41]:
sym.integrate(x * sym.acos(2*x)/sym.sqrt(1 - 4 * x**2), x)

-x/2 - sqrt(1 - 4*x**2)*acos(2*x)/4

In [42]:
sym.integrate(3*(x - 1)**2, (x, 1, 2))

1

In [43]:
sym.integrate(sym.sin(x)**3, (x, 0, sym.pi/2))

2/3

In [44]:
sym.integrate(1/(x*82 + 4*x + 13), (x, 1, sym.oo))

oo

In [45]:
# This integral does not converge but for some reason SymPy was executing this code forever
sym.integrate((2 + sym.sin(x))/sym.sqrt(x), (x, 1, sym.oo))

KeyboardInterrupt: ignored